#!/usr/bin/env python3
"""Turn a Robinson-projection world SVG into the app's `worldLand.ts`.

WHY A GENERATOR AND NOT THE SVG ITSELF. The file this reads is 470 separate
country paths with names, ids and per-country classes — a political map, at
2000 px wide, weighing 150 KB. What the app draws is a 240 px silhouette
behind a dot: no borders, no names, and nothing smaller than a pixel. So the
paths are merged into ONE (every country is land and fills the same, and a
merged outline is the right picture at that size — country borders at 240 px
are noise), islands below `--min-size` units are dropped, and the result is a
single string in a module the app imports LAZILY, so a page that shows no map
never fetches it.

Run it again when the source map changes:

    ./.venv/bin/python scripts/build_worldmap.py path/to/world.svg

The MIT notice travels INTO the generated file as a `/*! */` legal comment,
which is the one comment form a minifier keeps — the licence has to reach
whoever receives the bundle, and the bundle is what the server serves.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "frontend" / "src" / "shared" / "worldLand.ts"

NOTICE = """/*! World land outline — Robinson projection.
 *
 * Map data © 2020 Pareto Software, LLC DBA Simplemaps.com — https://simplemaps.com
 * Licensed under the MIT License; the full text is in licenses/MIT-simplemaps.txt
 * and in THIRD-PARTY-NOTICES.md.
 *
 * GENERATED by scripts/build_worldmap.py from the upstream SVG: the country
 * paths are merged into one silhouette and islands under a pixel are dropped.
 * Do not edit by hand.
 */"""


def path_points(d: str) -> list[tuple[float, float]]:
    """Every absolute point a path visits — enough for a bounding box.

    A curve contributes its END point only, which is what a bbox for "is this
    island bigger than a pixel" needs; the control points cannot take a shape
    far outside its own endpoints at this scale.
    """
    flat: list = []
    for a, b in re.findall(r"([A-Za-z])|(-?\d*\.?\d+(?:e-?\d+)?)", d):
        flat.append(a if a else float(b))
    out: list[tuple[float, float]] = []
    x = y = 0.0
    start = (0.0, 0.0)
    cmd = None
    i = 0
    while i < len(flat):
        t = flat[i]
        if isinstance(t, str):
            cmd = t
            i += 1
            if cmd in "Zz":
                x, y = start
            continue
        if cmd in ("M", "L", "T"):
            x, y = flat[i], flat[i + 1]
            i += 2
            if cmd == "M":
                start = (x, y)
                cmd = "L"
        elif cmd in ("m", "l", "t"):
            x, y = x + flat[i], y + flat[i + 1]
            i += 2
            if cmd == "m":
                start = (x, y)
                cmd = "l"
        elif cmd == "H":
            x = flat[i]; i += 1
        elif cmd == "h":
            x += flat[i]; i += 1
        elif cmd == "V":
            y = flat[i]; i += 1
        elif cmd == "v":
            y += flat[i]; i += 1
        elif cmd == "C":
            x, y = flat[i + 4], flat[i + 5]; i += 6
        elif cmd == "c":
            x, y = x + flat[i + 4], y + flat[i + 5]; i += 6
        elif cmd in ("S", "Q"):
            x, y = flat[i + 2], flat[i + 3]; i += 4
        elif cmd in ("s", "q"):
            x, y = x + flat[i + 2], y + flat[i + 3]; i += 4
        elif cmd == "A":
            x, y = flat[i + 5], flat[i + 6]; i += 7
        elif cmd == "a":
            x, y = x + flat[i + 5], y + flat[i + 6]; i += 7
        else:
            i += 1
            continue
        out.append((x, y))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("svg", type=pathlib.Path)
    ap.add_argument("--min-size", type=float, default=5.0,
                    help="drop a shape whose bbox is smaller than this in "
                         "viewBox units (2000 units = the whole world)")
    args = ap.parse_args()

    src = args.svg.read_text(encoding="utf-8")
    box = re.search(r'viewbox="([^"]+)"', src, re.I)
    if not box:
        print("no viewBox in that SVG", file=sys.stderr)
        return 2
    vb = [float(v) for v in box.group(1).split()]

    kept, dropped = [], 0
    for m in re.finditer(r'<path\b[^>]*\bd="([^"]+)"', src):
        d = m.group(1).strip()
        pts = path_points(d)
        if not pts:
            continue
        w = max(p[0] for p in pts) - min(p[0] for p in pts)
        h = max(p[1] for p in pts) - min(p[1] for p in pts)
        if max(w, h) < args.min_size:
            dropped += 1
            continue
        kept.append(d if d[0] in "Mm" else "M" + d)

    # Whitespace between commands is only needed between two NUMBERS; a letter
    # separates them by itself. That is most of what is left after the merge.
    data = " ".join(kept)
    data = re.sub(r"\s+", " ", data)
    data = re.sub(r"\s*([A-Za-z])\s*", r"\1", data)
    data = re.sub(r"(?<=[\d.])\s+(?=-)", "", data)

    OUT.write_text(
        NOTICE
        + "\n\n/** The map's own coordinate space — what `robinson.ts` projects into. */\n"
        + f"export const WORLD_VIEWBOX = {{ w: {vb[2]:g}, h: {vb[3]:g} }};\n\n"
        + "/** Every landmass, as one path. */\n"
        + "export const WORLD_LAND =\n  \"" + data.replace('"', '\\"') + "\";\n",
        encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(data) / 1024:.0f} KB of path data, "
          f"{len(kept)} shapes kept, {dropped} under {args.min_size} units dropped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
