// GENERATED — DO NOT EDIT.
//
// The words live in `docs/training/fields/*.md`, which is what the website's
// training page includes as well; `scripts/gen_field_help.py` compiles them
// into this table. Editing here is editing a copy: the next run overwrites
// it, and `tests/test_field_help.py` fails in the meantime.
//
// The values reach `t()` as data, so the i18n extractor cannot see them —
// `i18nCoverage.test.ts` harvests THIS table instead, which is why every
// paragraph here must stay byte-identical to its catalog key.
export const HELP: Record<string, string> = {
  "adapter.adapter-type":
    "Both add a small trainable layer over the frozen model; they differ in the shape of change they can express.\n\nA LoRA adds a 'low-rank' change: two thin matrices whose product is added to each targeted weight. Its capacity is exactly its rank — a rank-16 adapter can only ever make a rank-16 change, however long you train it. That is ample for a character, an object, a colour palette. It trains a little faster, it is the format every tool reads, and it carries better between related checkpoints: a LoRA trained on one finetune of a model usually still works on another.\n\nLoKr builds the change as a Kronecker product of two much smaller matrices instead. The saving comes from that structure rather than from throwing rank away, so the change is not confined to a thin slice of the weight while the file stays a small fraction of a LoRA's — under a tenth of the trainable parameters at rank 8. LyCORIS, whose method this is, suggests reaching for it when a LoRA 'does not learn well enough', and it is generally the better fit for styles and broad visual qualities, where a LoRA's rank ceiling is what you meet first. Its own caveats are the mirror image: slightly slower to train, and a very small LoKr transfers less well if you later swap the base model for a different finetune.\n\nWhat each can be USED by differs, and it is the file rather than the method. A LoRA is written in the layout every tool reads. A LoKr cannot be: that layout has a place for two matrices and nowhere to put a Kronecker factor. What it gets instead is a copy named the way ComfyUI names LoKr layers, and that works for the models whose layers ComfyUI addresses that way — FLUX.1, FLUX.1 Kontext and the Qwen-Image releases. On the others (SD 1.5, SDXL, Chroma, FLUX.2, Z-Image) a LoKr stays here: it works in the Evaluate tab and as the starting point of another job, but there is no file to hand over. On those, pick LoRA if the result has to leave this app.",
  "adapter.rank":
    "An adapter does not rewrite the model — it adds a small 'side channel' to certain layers, and rank is how wide that channel is: how much new information the adapter can hold.\n\nLow ranks (4–8) are plenty for a style or a colour palette and are very hard to overfit. Mid ranks (16–32) suit characters and objects with consistent details. High ranks (64+) mostly grow the file and the overfitting risk without helping, unless you are teaching a genuinely broad new domain.\n\nIt means slightly different things to the two adapter types. For a LoRA it is the hard ceiling on the change: a rank-16 adapter can only ever make a rank-16 change. For a LoKr it bounds only part of the structure, so a LoKr is not confined the way a LoRA is and its file grows far more slowly as you raise it — which is why the size estimate below is a figure for LoRA and a comparison for LoKr.",
  "adapter.alpha":
    "The adapter's output is multiplied by alpha ÷ rank before being added to the model, so alpha sets how loudly the adapter speaks at a given capacity. It works the same way for both adapter types.\n\nThe usual convention is alpha = rank, which makes the scale factor 1 and keeps behaviour comparable when you change rank. Setting alpha to half the rank is a common way to soften an adapter that comes out too strong. It interacts with the learning rate — halving alpha has a similar effect to halving the rate — so change one at a time.",
  "adapter.kronecker-factor":
    "LoKr expresses a weight's change as one small matrix combined with another. This number decides where the weight is cut into those two parts.\n\nLeft empty, the split is chosen to make the two parts as close to square as possible, which is where they are SMALLEST. Moving it either way grows the file, and the two directions are not the same thing: a low factor (4–8) pushes the weight into the second part, which is where the adapter's capacity is — that is the LyCORIS recipe for a LoKr that is not learning enough. A factor far above the square split grows the first, dense part instead, which costs size for nothing.\n\nMeasured on a 1280-wide layer at rank 8, against the same layer's LoRA: automatic 0.08x, factor 8 0.13x, factor 4 0.25x, factor 128 0.81x.\n\nThere is rarely a reason to set it. If a LoKr adapter is not learning enough, raise the rank first, then try a low factor.",
  "adapter.train-text-encoder":
    "The text encoder turns your prompt into the numbers the image model is conditioned on. Training it too lets the run attach meaning to a brand-new token — the classic reason to enable this is a made-up trigger word for a person or character.\n\nIt is also the fastest way to damage a model: an over-trained text encoder starts ignoring the rest of the prompt, and everything you generate drifts toward the training set. That is why it runs at a lower learning rate and stops partway through the run. For styles you rarely need it — the image side alone learns those well.\n\nWhich encoder that is depends on the model. Stable Diffusion and SDXL train their CLIP encoders. FLUX.1 trains CLIP-L and, unless the switch below leaves it out, T5-XXL; Chroma trains its T5, which is its only encoder. The models whose prompt is read by a language model (FLUX.2, Z-Image, Qwen-Image) offer no encoder training. A T5 adapter is expensive to train — several GB of activations per prompt — so on a card under 48 GB pair it with gradient checkpointing and, if that is not enough, with the text-encoder quantization further down: the adapter trains over the quantized weights exactly as it does over the quantized base model.",
  "adapter.include-the-large-encoder":
    "FLUX.1 reads a prompt with two encoders: CLIP-L, which produces one summary vector, and T5-XXL, which produces the sequence the transformer attends to word by word. This switch says whether the second one trains as well.\n\nCLIP-L is small (0.12B parameters) and cheap, and training it alone is what most FLUX LoRA tools mean by 'train the text encoder'. T5-XXL is forty times larger and keeps several GB of activations per prompt for its backward pass, but it is the encoder that carries the meaning of a word through the whole prompt — so it is the one to train when a trigger word or a new concept has to be understood in context rather than merely recognised.\n\nLeave it on unless memory is the problem. On a 32 GB card, pair it with gradient checkpointing and 8-bit quantization of the text encoder; a 48 GB card runs it at full precision. The switch is only shown for models that have both kinds of encoder.",
  "adapter.text-encoder-lr":
    "A separate, gentler learning rate for the text encoder. It is far more fragile than the image side: the same rate that trains the image model nicely will overshoot here and start dissolving the model’s grasp of ordinary words.\n\nLeaving this empty uses half the main rate, which is the usual convention. If prompts start behaving oddly — words being ignored, everything drifting toward the training set — this is the first number to cut.",
  "adapter.stop-te-after":
    "At this fraction of the run the text encoder is frozen and only the image side keeps training. 0.5 means the first half trains both, the second half trains the image model alone.\n\nThe reasoning: the association between your trigger word and the concept is learned early, while visual detail keeps improving for much longer. Freezing early locks in the word without letting the encoder keep drifting toward the training captions.",
  "adapter.only-these-layers":
    "By default the adapter attaches to every attention layer in the image model. This narrows that to the layers whose name contains one of the words you list.\n\nWhy you might: different parts of the network do different jobs. The later ones carry more of what a picture LOOKS like, and the earlier ones more of how it is put together — so training only part of the network is how a style is learned without also disturbing composition and anatomy. It also makes the adapter smaller and each step faster, since there is less to train.\n\nThe names come from the model itself, and the chevron at the end of the field lists the ones worth knowing for the architecture you picked — clicking one adds or removes it, and a tick marks the ones the field already holds. For SD and SDXL they are down_blocks, mid_block and up_blocks, plus attn1 (the picture attending to itself) and attn2 (where the prompt gets in); for the newer transformer models, transformer_blocks and single_transformer_blocks. The field stays free text, because you can be as coarse or as fine as you like: 'up_blocks' takes a whole third of a UNet, 'transformer_blocks.12' takes one block, 'to_k' takes one kind of projection everywhere. The job's page draws a map of the whole model once a run has started.\n\nIf what you type matches no layers at all, the run stops and says so rather than training an adapter attached to nothing — which would otherwise look exactly like a normal run that learned nothing.",
  "adapter.except-these-layers":
    "The same kind of list, subtracting instead of selecting. A layer whose name matches anything here is left out even if the field above selected it.\n\nIt is the easier way to say 'everything except' — excluding 'down_blocks' is shorter and stays correct if the model gains a block, where listing every other block by hand does not.",
  "base-model.model":
    "The pretrained model this job starts from. Everything trained here is a modification of it, so its strengths and its blind spots carry over: an anime-trained base stays anime-flavoured, a photographic one stays photographic.\n\nSD 1.5 is small, fast and forgiving — the easiest place to start and the one that fits the least hardware. SDXL is the mainstream quality choice at 1024 px and needs noticeably more memory. Everything below them is a flow-matching transformer: they follow a long prompt far better and they are all much hungrier, because the text encoder is a language model that has to stay resident whatever else you economise on — which is why the largest of them are offered as a LoRA only. Among those, the smallest one that fits your card is usually the right answer, and the estimate under these settings says which those are.\n\nThe choice also fixes what the result is compatible with afterwards: an SDXL LoRA only works with SDXL models. Releases that share an architecture are listed together, and those are the ones a LoRA carries between.",
  "base-model.method":
    "An adapter leaves the base model untouched and trains a small add-on (a few dozen MB) that is layered on top at generation time. It is quick, fits ordinary hardware, can be mixed with other adapters and dialled up or down by weight — and it is enough for styles, characters, objects and most concepts. There are two kinds, LoRA and LoKr, and the Adapter section below picks between them; LoRA is the one to start with.\n\nA full finetune rewrites every weight of the model. It produces a multi-gigabyte model of its own, needs far more VRAM, far more images and much lower learning rates, and it can forget things it used to know. Reach for it only when you are moving the model into a genuinely different domain, not to teach it one more subject.",
  "batch-seed.batch-size":
    "How many images are averaged into a single weight update. Bigger batches give a smoother, less noisy training signal and run faster per image, but memory use grows almost linearly — this is usually the first thing to hit an out-of-memory error.\n\nOn consumer hardware batch 1–4 is normal. If you want the stability of a bigger batch without the memory, leave this at 1 and raise gradient accumulation instead: it produces the same averaged update, just spread over several passes.",
  "batch-seed.gradient-accumulation":
    "Runs N batches back to back, adds up their gradients, and only then updates the weights — mathematically close to training with an N× larger batch, but only one batch is ever in memory.\n\nThe cost is time: each update now takes N passes, so a step is N× slower. Effective batch = batch size × accumulation; that product is what to compare between setups.",
  "batch-seed.seed":
    "One number that seeds every random choice this job makes: which images are drawn in which order, which crop of each, which tags are picked, and the noise used for the test samples.\n\nRe-running with the same seed and the same settings reproduces the run — that is what makes it possible to change one parameter and know the difference you see came from that parameter and not from luck. Change it deliberately when you want a genuinely different draw from the same dataset.",
  "checkpoints.keep-step-snapshots":
    "With this off, the job keeps only the rolling checkpoint it needs to resume after a pause — when the run ends you get exactly one result, whatever the final step happened to look like.\n\nWith it on, a permanent snapshot is written at a fixed cadence, and every one of them can be generated with in the Evaluate tab. Since the ideal number of steps is impossible to know up front, this is how you avoid guessing: train past the point you think is right and pick the snapshot that actually looks best.",
  "checkpoints.cadence-measured-in":
    "A step is a fixed amount of work and an epoch is one pass over every training image, so the two cadences drift apart as a dataset grows — “every 500 steps” is most of a small run and a fraction of a big one, while “every epoch” means the same thing in both.\n\nHow many steps an epoch takes is worked out when the run starts, because only the built dataset knows how many entries it has. That is also why the disk estimate below can only be given when the run's length is set in epochs too.",
  "checkpoints.checkpoint-every":
    "Every snapshot is a usable model file: the Evaluate tab can generate with any of them, so you can compare one pass against another and keep whichever looks best.\n\nCounted in passes, the cadence follows the dataset: add pictures and the snapshots stay one-per-pass rather than quietly becoming more frequent than a pass. The trainer prints what it works out to in steps, so the timeline and the log still agree about what a checkpoint is.",
  "checkpoints.checkpoint-every-2":
    "Every snapshot is a usable model file: the Evaluate tab can generate with any of them, so you can compare step 1000 against step 2500 and keep whichever looks best. This is the main defense against overfitting — you do not have to guess the right number of steps up front, you just pick the checkpoint that looks right afterwards.\n\nSnapshots cost disk space (the estimate is shown below), which is what the keep-limit is for.",
  "checkpoints.keep-the-last":
    "When a new snapshot is written the oldest of these is deleted, so the window never grows. A LoRA snapshot is small (tens of MB) and you can comfortably keep a dozen; a full finetune snapshot is the size of the whole model, so two or three is already a lot of disk. The resumable checkpoint is kept outside this limit and never counts against it.",
  "checkpoints.also-keep-one-in":
    "Milestones that stay for good, spread across the whole run: with a cadence of 200 steps and one in 5, the snapshots at 1000, 2000, 3000 … are never deleted. This is what lets you compare an early style against a late one after the run is over, and it combines with the window above — a snapshot is kept when either rule wants it. 0 turns it off.",
  "crops-flips.max-aspect-ratio":
    "Images are not squashed to a square. They are sorted into 'buckets' of different shapes but equal pixel area, and each image trains at the bucket closest to its own proportions.\n\nThis cap limits how extreme those shapes get. At 2 the widest bucket is 2:1 and the tallest 1:2; anything more extreme is cropped into the nearest allowed shape. Raising it preserves very wide or very tall images at the cost of more buckets (and slightly less efficient batching).",
  "crops-flips.random-crop":
    "After an image is fitted to its bucket there is usually a little slack on one axis. With random crop that slack is spent differently every time the image comes up, so the model sees slightly different framings of the same picture — cheap variety that helps small datasets generalise.\n\nCrops are bounding-box aware: if a tag in the composed prompt has a box on the image, the crop is steered to keep that box inside the frame, so a prompted subject is never cropped away from under its own tag. Turn it off when exact framing matters (logos, text).",
  "crops-flips.horizontal-flip-probability":
    "Chance that a visit sees the image mirrored left-to-right. It doubles the apparent variety of a small dataset for free, and tag bounding boxes are mirrored along with the pixels.\n\nLeave it at 0 whenever left and right carry meaning: text, logos, asymmetric clothing or hairstyles, characters with a scar or an eyepatch on one side. For generic photographic subjects 0.3–0.5 is a common choice.",
  "crops-flips.never-flip-images-tagged":
    "Flipping is free variety for most pictures and quietly destructive for some: mirrored text is unreadable, a logo becomes a different logo, and a character whose scar or parting is on one side learns to have it on both.\n\nRather than pick one setting for the whole dataset, name the tags that mark those images. An image carrying any of them is never mirrored — not in the cache, not on any visit — while the rest of the dataset keeps the augmentation.",
  "crops-flips.never-flip-images-whose-tags-are-marked":
    "The same veto, said once in the library instead of tag by tag here. Any tag the Tags tab marks with one of these meta tags switches mirroring off for every picture carrying that tag.\n\nIt is worth the indirection for the reason a list of names goes stale: “text”, “logo”, “signature”, “left-handed”, a dozen characters with an eyepatch — the list in a job's settings is right the day it is written and wrong the next time somebody adds a tag it should have held. Marking the tags themselves puts the fact where the tag is, so a tag added later carries it into every run automatically, and a job written before that tag existed still does the right thing.\n\nBoth lists apply: a picture is left unmirrored if it carries a tag named above OR a tag marked here.",
  "degraded-copies.visits-per-clean-visit":
    "The clean picture is always in the dataset — a degraded copy is an extra sample, never a replacement, and every clean picture keeps the same weight as every other one.\n\nWhat this sets is the ratio between the two. It cannot conjure steps: a run has a fixed number of them, so degraded samples take their stated share. The mix below says what that works out to.",
  "degraded-copies.cached-variations-per-picture":
    "The value inside a range is drawn once per picture and kept, so the degraded copy can be cached instead of re-encoded every epoch. With one variation the dataset still covers the whole range — each picture simply sits at its own point on it.\n\nRaise this to give a single picture several strengths to be seen at. It multiplies the number of cached files directly, which the count under the list tracks.",
  "degraded-copies.add-tags":
    "These are what make the degradation trainable rather than just harmful. The model sees the same picture twice — once clean, once spoiled and carrying these words — and learns them as the difference.\n\nThey are added to the prompt unconditionally, because every rule that could drop them would leave a bad picture in the dataset with nothing saying so.",
  "degraded-copies.remove-tags-if-present":
    "A copy that has been through a codec is not 'masterpiece' any more, and leaving the word on it teaches the model that the word means nothing.\n\nTags are removed before the random pick, so the freed slot is filled by another tag rather than lost — and any tag that was only implied by a removed one goes with it, or removing 'masterpiece' while 'high quality' stays removes nothing at all.",
  "degraded-copies.remove-tags-marked":
    "The list above, named by what the library says about a tag. Any tag marked with one of these meta tags comes off this sample.\n\nWhat it is for is that the claims a degraded copy no longer supports are a CATEGORY, not a list: 'masterpiece', 'absurdres', 'high quality', 'official art' and whatever the next dump adds are all \"a claim about the picture's quality\". Marking them once means every variant of every job drops them, and the same mark can then say something different per method — a 'resolution_claim' mark belongs on a resize variant's list, a 'fidelity_claim' on a JPEG one.",
  "degraded-copies.only-pictures-whose-tags-are-marked":
    "The line above by mark rather than by name: a picture is degraded only if it carries a tag the library marks this way.\n\nChecked against the picture's effective tags, so a tag it only carries by implication counts too. With both lists empty, every picture is fair game.",
  "degraded-copies.never-pictures-tagged":
    "Checked against the picture's effective tags, so a tag it only carries by implication counts too, and a picture that is skipped costs no encoding, no cached file and no disk at all — the check happens before anything is made.",
  "degraded-copies.never-pictures-whose-tags-are-marked":
    "The veto by mark, and it wins over both lines above exactly as the named list does.\n\nThe pair is what makes a degrading run safe on a mixed library: mark the pictures that are already poor — a 'low_quality' or 'rescan' mark on the tags that say so — and no variant can ever degrade one of them further, however broadly the \"only pictures\" side is drawn.",
  "device.gpu":
    "Which GPU this job runs on. The queue treats every GPU as its own lane: it starts the first waiting job whose GPU is free, so two jobs pinned to different GPUs train side by side while jobs sharing one GPU take turns.\n\nAutomatic means the machine's first GPU — on a single-GPU machine there is nothing to choose.",
  "instruction-selection.only-instructions-tagged":
    "Items often carry more than one caption: a one-line description and a paragraph, a translation, a machine draft someone approved. They are not interchangeable, and a run that mixes them teaches the model to answer the same picture in several different registers.\n\nMeta tags are how a caption is labeled in the library — “long”, “alt text”, “German” — so naming one here picks that kind of caption throughout the dataset without touching the captions themselves. An item whose captions are all filtered out simply trains with no caption text, exactly as an item with no captions does.",
  "instruction-selection.an-item-with-several-captions":
    "Items often carry more than one caption — a short one and a long one, a translation, a machine draft somebody approved.\n\nONE AT RANDOM gives the item a single visit each pass and draws a different caption each time, so the whole set is seen across a long run and an item counts once however many ways it has been described.\n\nEVERY CAPTION gives it one visit per caption, so all of them are used every pass — and an item with ten is therefore seen ten times, which is usually an accident of tooling rather than a claim that the picture matters ten times as much.\n\nEVERY CAPTION, SHARED is that with the accident removed: each caption still gets its visit, and together they carry one item's worth of gradient.",
  "instruction-selection.skip-instructions-tagged":
    "The other half of the same lever, and usually the easier one to maintain: rather than name every kind of caption you want, name the few you do not.\n\nThe common cases are captions kept for a purpose other than training — a note to yourself, a source credit, an unreviewed machine draft — and captions in a language the model was not trained on. Excluding wins over including, so a caption carrying both an included and an excluded tag is left out.",
  "length-learning-rate.length-measured-in":
    "A STEP is one batch pushed through the model and one update of the weights — a fixed amount of work whatever the dataset holds. An EPOCH is one pass over every training image, so the same number means a longer run on a bigger set and the model sees each picture the same number of times either way.\n\nEpochs are usually the easier thing to reason about: “each image about ten times” transfers between datasets, where “3000 steps” does not. The exact step count is worked out when the run starts, because only then is it known how many entries the dataset has — a film contributes its frames, a degraded copy is an extra sample, and an item can contribute one per caption.",
  "length-learning-rate.epochs":
    "How many times the run works through every training image. Each pass visits every entry exactly once, in a fresh random order.\n\nWhat counts as an entry is the dataset after it has been built, not the number of pictures you selected: a video contributes one entry per kept frame, a degradation variant adds an extra sample beside the clean picture, and with “every caption” an item contributes one entry per caption. That is why the step count appears when the run starts rather than here.",
  "length-learning-rate.total-steps":
    "One step = one batch of images pushed through the model, followed by one update of the weights. What matters is roughly steps × batch size relative to your dataset size: with 30 images and batch 1, 3000 steps means the model sees every image about 100 times.\n\nToo few steps and the concept never 'sticks' — samples still look like the base model. Too many and the LoRA memorises the training images: prompts start reproducing backgrounds and poses you never asked for, and unrelated prompts get contaminated. Since test samples are rendered along the way and every checkpoint can be used, it is safer to train a bit too long and pick an earlier checkpoint than to stop too early.",
  "length-learning-rate.learning-rate-multiplier":
    "The Prodigy optimizer measures how far the weights have moved from where they started and derives a learning rate from that, so the rate is not something you set here — it comes out of the run.\n\nWhat this field does is scale the answer. 1 accepts it as found and is what you want almost always. Below 1 is a brake, worth reaching for if the run overshoots and samples come out burnt; above 1 pushes harder, which is occasionally useful on a very small dataset.\n\nProdigy needs a few hundred steps to work its estimate up from nearly nothing, so early samples in a Prodigy run look untrained even when everything is fine. Judge it from about a fifth of the way in, not from the first sample round.",
  "length-learning-rate.learning-rate":
    "How far the weights move on every update. It is the single most sensitive setting here.\n\nToo high and training diverges: samples turn into over-saturated, high-contrast mush ('deep fried'), often within a few hundred steps. Too low and nothing visibly changes no matter how long you wait. Typical values: 1e-4 for a LoRA, 1e-5 or lower for a full finetune (which touches every weight and needs far gentler updates).\n\nLearning rate and total steps trade off against each other — halving the rate roughly doubles the steps needed. If early samples look burnt, halve it; if they look identical to the baseline after a third of the run, double it.\n\nIf finding this number is the part you would rather not do, the Prodigy optimizer (Memory & speed) works it out for itself.",
  "length-learning-rate.lr-schedule":
    "Shapes the learning rate over the run instead of holding it fixed.\n\nCosine starts at the full rate and eases down to zero: big strokes early to learn the concept, fine strokes late to settle the details — the safe default. Linear decay does the same in a straight line. Constant keeps full speed throughout, which learns fastest but tends to still be 'wobbling' when the run ends. Constant + warmup ramps up over the first steps, then holds; the ramp protects the delicate text encoder from a hard first hit.",
  "length-learning-rate.warmup-steps":
    "Instead of hitting the model with the full learning rate from step one, warmup ramps it up from near zero over the first N steps.\n\nThe first updates are the most dangerous ones: the optimizer has no history to smooth them out yet, and a hard first push can knock the model somewhere it never fully recovers from. Ramping in avoids that. A few hundred steps, or roughly 5% of the run, is typical — and it matters most when the text encoder is being trained or the learning rate is on the high side. With a cosine schedule on a plain LoRA you can usually leave it empty.",
  "masked-regions.mask-out-regions-tagged":
    "Some pictures are worth training on except for one rectangle: a watermark, a shop’s caption strip, a censor bar. Left alone, the model learns the rectangle along with the picture — a run over watermarked photographs reliably teaches the watermark. Throwing those pictures out costs the dataset; this keeps them and hides the rectangle from training instead.\n\nThe regions come from the boxes already on the tag: draw a box for `watermark` in the annotator (or let the watermark detector’s tag carry one), name the tag here, and every image carrying such a box trains with the loss inside it turned down. Where a subject tag has no drawn box, its detected faces stand in, exactly as they do for crop-aware training. An image whose named tags have no boxes trains completely normally — nothing is masked there.\n\nOnly the LOSS is masked. The pixels still pass through the image encoder, so the cached latents are the ordinary ones shared with unmasked runs, and nothing is re-encoded when this setting changes. The mask lives in latent space, where one cell covers 8×8 pixels rounded outward to whole cells — so it cannot hide anything much thinner than that, and a pixel-accurate outline is not something it can promise. It also cannot conjure what is UNDER the watermark: the model simply receives no signal about that area, from this picture.\n\nPairs naturally with a tag the prompt always includes (Always include under Tag selection): the prompt says the watermark is there, the mask stops the pixels teaching it, and at generation time the model has no reason to produce one unprompted.",
  "masked-regions.mask-out-regions-of-tags-marked":
    "The same rule, stated once in the library instead of tag by tag here. A meta tag put on the tags whose boxes should never teach — `masked`, say — covers every such tag at once, including ones created after this job was written.\n\nThe list is resolved to tag names when the dataset is built, so the job’s log says how many images actually carried a masked region. A run where that line says zero has a rule pointing at tags nobody drew boxes for.",
  "masked-regions.masked-region-weight":
    "What a cell inside a masked box still counts for. 0 hides the region entirely, which is the usual choice for a watermark — there is nothing in it worth a whisper. A small value (0.05–0.2) keeps a faint signal, which can be worth it when the boxes are generous and cover real picture around the thing being hidden.\n\n1 is the unmasked loss, so setting it there is the same as clearing the tag lists. Where an image also trains with an alpha mask, the two multiply: a masked region on a transparent background is doubly not the picture.",
  "memory-savers.gradient-checkpointing":
    "Normally every intermediate result of the forward pass is kept in memory because the backward pass needs it. With gradient checkpointing most of them are thrown away and recomputed on demand instead.\n\nThat cuts memory use substantially — often the difference between a run that fits and one that crashes — at the cost of roughly a quarter more time per step. Turn it on when you hit out-of-memory errors, or from the start for full finetunes and large models.",
  "memory-savers.attention-slicing":
    "Attention is where a diffusion step's memory goes: computed in one piece it holds a score matrix per attention head for every position in the image, growing with the square of the resolution.\n\nModern PyTorch computes attention with fused kernels that never build that whole matrix, so on an NVIDIA GPU the default is already both fast and memory-efficient — leave this off. Turn it on only when a run is memory-bound and won't fit otherwise: slicing walks the computation in chunks so only one exists at a time, lowering peak VRAM for roughly 10% more time per step.\n\nOn Apple silicon the trainer uses the efficient default attention and does not slice, so the setting is fixed off there.",
  "memory-savers.optimizer":
    "The optimizer is what actually turns gradients into weight changes. It does that using running statistics it keeps for every weight being trained — and those statistics are memory, which for a full finetune is usually most of what the run needs.\n\nAdamW is the standard choice and the safest. It keeps two statistics per trained weight, so a full finetune pays for the model roughly three times over: the weights themselves, plus two more of the same size.\n\nAdamW (8-bit) stores those two statistics at one byte each instead of four. It is a smaller saving than it sounds, because the weights and their gradients do not shrink, and it needs an NVIDIA or AMD (ROCm) GPU — elsewhere the run says so and uses plain AdamW.\n\nAdafactor replaces the larger of the two statistics with a per-row and a per-column summary of it, which is a fraction of the size. It saves considerably more than the 8-bit variant and it runs on every GPU, including Apple silicon — where it is the only memory saving available at all, since the 8-bit variant cannot run there. What it costs is a little stability: it usually wants a slightly higher learning rate than AdamW, so if a run learns nothing after a few hundred steps, raise the rate before changing anything else.\n\nProdigy is a different kind of answer. It measures how far the weights have travelled from where they started and works the learning rate out from that as it goes, which removes the one setting here that genuinely has to be found by trial: the right rate depends on the model, the dataset size and what is being taught, so a value that suits one job is wrong for the next. With it selected, the learning rate on the Optimization page becomes a multiplier on what it finds, and 1 means 'as found'. It uses a little more memory than AdamW, and it needs a few hundred steps to work its estimate up — so early samples look untrained even when the run is fine.\n\nFor LoRA training the memory differences are a rounding error, since only the small adapter has optimizer state. Leave it on AdamW for a first run; reach for Prodigy when you are tired of guessing the rate, and for Adafactor when a full finetune will not fit.",
  "memory-savers.cache-latents":
    "The model does not work on pixels. Every image is first compressed by the VAE into a small 'latent' — and since the training images never change, doing that once and keeping the result is pure profit.\n\nSo before the run starts, every image is encoded once and written to disk. Training then reads latents instead of JPEGs, which is faster per step, and the VAE can be dropped from memory entirely for the rest of the run. Random crops still vary from visit to visit — they happen on the latent, in steps of 8 pixels, which is far finer than the crop jitter itself.\n\nThe cost is disk space and a few minutes up front. The cache is reused across runs on the same files.",
  "noise-levels.train-on":
    "Every training step takes a picture, adds some amount of noise to it, and asks the model to undo that. How much noise is picked fresh each time — and the two extremes teach completely different things.\n\nAt HIGH noise there is barely a picture left, so all the model can learn is layout: what is where, how big, the overall shape and colour. At LOW noise the composition is already settled and what is left to learn is detail and texture — edges, surfaces, small features.\n\nSo where a run spends its steps decides what it mostly teaches. A style is largely texture; a character's proportions are largely layout.\n\n'The model's own' is what this model family has always done here, and is the right answer unless you have a specific reason: the older models spread their steps evenly, and the newer ones concentrate on the middle, which is what their published recipes do and part of why they train efficiently. 'Evenly' spreads across the whole range. 'Bell curve' is the newer models' behaviour made adjustable, so you can lean it towards layout or towards detail. 'Cosine' leans towards higher noise without abandoning the low end.\n\nChanging this does not make a run better or worse in general — it moves what the run is good at.",
  "noise-levels.aim-at":
    "Where the centre of the bell curve sits along the noise range.\n\n0 puts it in the middle, which is what the newer models do by default and a good place to stay. Move it positive and the run spends more of itself at high noise, learning layout and composition — useful when what you are teaching is a shape or an arrangement. Move it negative and it spends more at low noise, learning detail and texture — useful for a style, a medium, a surface quality.\n\n±0.5 is a noticeable lean and ±1 is a strong one. Beyond ±2 the run largely stops seeing one end of the range at all.",
  "noise-levels.spread":
    "The width of the bell curve.\n\n1 is the standard setting. Smaller values concentrate the run on a narrow band around wherever you have aimed it, which sharpens what it teaches at the cost of everything else. Larger values spread it out and reach both extremes more often, which is closer to training evenly.\n\nIf you are unsure, leave it at 1 and move the aim instead — the aim is the setting that changes what the run learns, and this one changes how single-minded it is about it.",
  "precision-quantization.precision":
    "How many bits each number uses while training. bf16 (16-bit 'brain float') keeps the same range as full precision with less accuracy per number — half the memory, no practical quality loss, and the modern default on any GPU that supports it.\n\nfp32 is full precision: twice the memory and slower, used automatically as a fallback where bf16 is unavailable. fp16 also uses 16 bits but has a much smaller range and tends to overflow into NaNs during training — fine for inference, avoid it here.",
  "precision-quantization.half-precision-master-weights":
    "Only for a full finetune, and only there because that is the one run where the trained weights ARE the memory. A full finetune keeps a full-precision copy of every weight it trains, plus a gradient the same size — on SDXL that is 10 GB and 10 GB, against about 2 GB for everything frozen and, with Adafactor, almost nothing for the optimizer's own statistics. This stores them at 16 bits instead of 32.\n\nIt works by carrying what the rounding drops. That is not a detail: a training step is far smaller than the smallest change a 16-bit weight can represent, so stored the ordinary way every single update would vanish and the model would never move — measured on a real (small) model over 300 steps, 47% of the weights never moved at all. Keeping the remainder in a third buffer and adding it back to the next update means nothing is lost, only deferred until it is large enough to change the stored value: a hundred updates each a tenth of a step's worth move the weight on the tenth, rather than never.\n\nWhat it costs is that third buffer, the same width as the weights — so the saving is a third of the memory rather than a half. What it does not cost is quality: over the same 300 steps the loss fell to 0.470 with full-precision weights and 0.471 with these. An earlier version rounded the updates up or down at random instead, which is smaller still (no third buffer) and measurably worse: it learns by an average that is right and an individual step that is wrong, so the loss reached only 0.53, and the noise grows as the learning rate falls — which is exactly what a cosine schedule does for the whole second half of a run.\n\nIt cannot be used with Prodigy, which works its learning rate out across all the weights at once and so cannot be stepped one at a time.",
  "precision-quantization.base-model-quantization":
    "The base model is by far the largest thing in memory, and during LoRA training it never changes — only the small adapter does. Quantization stores those frozen weights at lower precision while the adapter keeps training in full precision on top (the approach known as QLoRA). It is the WEIGHTS that shrink, not the arithmetic: every matmul still runs at the precision set above, on values converted back as they are used.\n\n8-bit float (fp8) and 8-bit (int8) both roughly halve the base model's memory for a small quality cost — an fp8 round trip moves a weight by a few percent. They differ in what they need: fp8 is a plain data type your GPU either has or hasn't (NVIDIA's Ada and Hopper generations and newer; Apple silicon has no fp8 type at all). int8 runs everywhere — through bitsandbytes on NVIDIA, and through quanto on Apple silicon, where it is what makes the largest models trainable at all. 4-bit (NF4) quarters the weights and is what makes very large models trainable on consumer NVIDIA cards, at a more visible cost in fidelity; it needs bitsandbytes too.\n\nOn hardware that cannot do what you picked, the run stops with a clear message rather than silently using full precision and blowing the memory budget you planned around.",
  "precision-quantization.quantize-the-text-encoder":
    "The base model is not the only large thing held in memory: the text encoder that reads your prompt is frozen in exactly the same way, and on the biggest models it is a substantial share of the total — around 17 GB of Qwen-Image's 58, or 10 of Chroma's 28.\n\nQuantizing it applies the scheme chosen above to those weights too. Measured on Apple silicon, a Qwen-Image LoRA run goes from about 37 GB to 30 with this on, which is the difference between needing a 48 GB machine and a 36 GB one.\n\nWhat it costs is a little fidelity in how the prompt is read, which is why it is off by default — a run that already fits has no reason to pay it. It can be combined with training the text encoder: the adapter trains in full precision over the quantized weights, exactly as it does over the quantized base model, which is what makes T5-XXL trainable on a 32 GB card.",
  "precision-quantization.keep-the-text-encoder-on-the-cpu":
    "The row above makes the text encoder smaller; this one takes it off the graphics card altogether. Its weights stay in ordinary system memory and each prompt is turned into an embedding there, so the encoder occupies no VRAM at all — where quantizing it leaves roughly a third of it resident.\n\nMeasured on an RTX 5070 Ti at 4-bit, this takes Chroma from 9.6 GB to 5.3 and FLUX.1 from 11.4 to 7.0, which was enough to train FLUX.2 Klein at a resolution that did not previously fit.\n\nWhat it costs is one pass over the encoder per step, on the processor instead of the graphics card — and the next batch's prompt is encoded while the current one trains, so the card only waits where the processor is slower than a whole step. Measured on a 16-core desktop, T5-XXL takes about 1.3 seconds a prompt: a 1024-pixel step on an RTX 5090 hides that entirely, a 512-pixel step (half a second) does not. It cannot be combined with training the text encoder, which would mean doing that training on the processor.",
  "query-weight.a-weight-buys":
    "Both spend the same ratio; they differ in what they spend it on.\n\nSEEN MORE OFTEN is the classic behaviour: a weight-2 query's pictures get twice the visits, which means they take those visits from the rest — a fixed-length run spends more of itself on them and less on everything else.\n\nCOUNTED FOR MORE gives every picture the same number of visits and multiplies the weighted ones' effect on the weights instead. Nothing loses coverage; the emphasis comes out of the gradient rather than out of the other images' training time. It is the better default when the queries are different KINDS of picture rather than different amounts of importance.",
  "regularization.how-much-reminders-count":
    "Regularization pictures are in the run to hold the model's existing idea of a thing in place while you teach it something new. This is how much each of them counts against a training picture, which counts 1.\n\n1 is the classic setting and a good starting point. Lower it if the run seems reluctant to learn what you are actually training — the reminders are pulling too hard. Raise it if what you are training keeps leaking into everything else of the same kind, which is the problem they exist to solve.\n\nThis is separate from a query's weight, which decides how OFTEN those pictures come up. How often and how much are different questions: a set of reminders is usually wanted often but quietly.",
  "resolutions.resolutions":
    "The sizes images are trained at, each given as one number that stands for a pixel budget: 1024 means 'about a megapixel', which every aspect-ratio bucket then spends differently — 1024×1024, or 1216×832, or 832×1216.\n\nMatch them to what the base model was trained on (1024 for SDXL, Chroma and FLUX.2, 512 for SD 1.5); training far above that teaches little and costs a lot, while training below it is a genuine speed and memory lever at the price of fine detail. Cost scales with the area, so 768 is nearly half the work per step that 1024 is. The size the list marks as default is the model's own, and a job set to it follows whichever model it is pointed at.\n\nPicking more than one trains the same pictures at each of them. A model that has only ever seen a subject at 1024 has learnt it together with the canvas it was on: asked for something smaller it tends to answer with a crop or a doubled-up version of the same framing. Several sizes separate what the model learns about the subject from what it learns about the shape of the picture.\n\nEach size is a full family of buckets, and every image joins the ones it is large enough for — which is the other half of what this is for. Under Never upscale a 700-pixel scan is simply left out of a 1024 run; add 512 and it trains there instead of being dropped, while the large pictures keep training at both.\n\nIt is not free. A size is another pass over the dataset in every epoch and another cached latent per picture, and the batches at the largest one decide the peak memory — so adding a size above the others raises what the run needs on the card, and adding ones below mainly makes an epoch longer. Two or three an octave apart (512, 768, 1024) is the usual shape; at most five.",
  "resolutions.never-upscale":
    "An image smaller than its bucket has to be enlarged to train at that size, and enlarging invents detail that was never in the picture: soft edges, smeared texture, the interpolation's own look. Trained on, that is what the model learns the subject looks like.\n\nThis is on by default. Those images are left out while the dataset is built — before anything is encoded, so they cost no time and no cache — and the run says how many it dropped. It is asked per resolution, so a picture too small for the largest size still trains at a smaller one rather than being dropped from the run; turn it off for a small dataset, where a slightly soft picture is usually worth more than no picture.",
  "source.build-prompts-from":
    "Every image needs a text prompt to train against, and this decides where that text comes from.\n\nTags give you control: they can be shuffled, sampled, balanced and dropped, which is what makes a model respond to individual words rather than to whole memorised sentences. Captions give you natural language and relationships between things (“a red car parked in front of a house”) that a tag list cannot express. Caption + tags puts the sentence first and the tag list after it, which is the usual choice when your library has both.\n\nNothing (trigger word only) is the fourth answer: every prompt is the trigger word and nothing else. That is how a trigger is taught to mean the pictures themselves rather than to modify something a prompt has already said — the usual choice for a style or a character where the pictures are the whole point and nothing about them varies in a way you want to be able to ask for. It is also the only source under which every selected picture is in the run whatever it carries, since there is nothing it could be missing; tag and caption selection do not apply. Without a trigger word it would train on an empty prompt, which is the dropout signal rather than a concept, so set one.",
  "source.trigger-word":
    "A word put at the front of every training prompt, which you then type to summon what was trained. It works because the model binds what it sees to the words it is given.\n\nPick something the model has no prior opinion about: 'ohwx', 'sks style', an invented name. A common word like 'portrait' would blend your concept into everything that word already means. Leave it empty when you are teaching an existing concept rather than a new one.",
  "tag-selection.always-include":
    "Tags listed here bypass the random subset pick: if the image has the tag, the prompt gets it.\n\nThe point is honesty about things the model would otherwise learn silently. If a third of your images carry a watermark and the word never appears in a prompt, the model concludes watermarks are simply part of how these pictures look — and paints them into everything. Naming it every time attaches the concept to the word instead, and you can then suppress it at generation time.\n\nSame reasoning for anything that is present but not wanted: a signature, a logo, a heavy filter. A tag is never forced onto an image that does not have it.",
  "tag-selection.always-include-tags-marked":
    "The rule above, named by what the library says ABOUT a tag rather than by the tag. Any tag marked with one of these meta tags bypasses the random pick — again only where the image actually has it.\n\nA meta tag put on “watermark”, “signature” and “logo” once means every run treats them that way, including runs written before the third of them existed. The two lists are unioned, so naming a tag here and above is simply the same instruction twice.",
  "tag-selection.exclude":
    "Tags removed from every prompt before it is used, while staying on your items.\n\nTwo common cases. Housekeeping tags that describe your workflow rather than the picture (“check-later”, “scan”, quality ratings) teach the model nothing and dilute the prompt. And when you are training a concept behind a trigger word, excluding the plain tag for that concept keeps the meaning attached to the trigger instead of leaking into the everyday word.",
  "tag-selection.exclude-tags-marked":
    "The same, one level up: any tag the library marks with one of these meta tags is stripped from every prompt.\n\nThis is the one to reach for when the exclusions are a KIND of tag rather than a list of them. Quality ratings, scan notes, the booru's own housekeeping words — mark them “noprompt” in the Tags tab and every run drops them, instead of every job carrying a list that has to grow with the vocabulary.\n\nIt is not the same as a skipped tag GROUP below. This one is about the tag wherever it appears; that one is about a grouping on one item, and a tag placed in an excluded group and also somewhere else survives it.",
  "tag-selection.skip-tag-groups-tagged":
    "Per-item tag groups are how a library keeps what a picture shows apart from notes about it — a “Notes” group holding “to redraw” and “bad scan”, a group for someone else's tags you have not checked. Those words are useful in the library and wrong in a prompt.\n\nMarking the group with a meta tag and naming it here is what makes that separation reach training, without maintaining a parallel exclude list of individual tags that grows every time you add one.\n\nTwo details keep it honest. A tag placed in an excluded group AND somewhere else — another group, or ungrouped — stays, because it reaches the item by a route you did not exclude. And a broader tag that was only implied by dropped tags is dropped too: excluding a group holding “poodle” would otherwise leave “dog” in the prompt.",
  "tag-selection.min-tags-per-prompt":
    "The fewest tags a prompt may contain. Together with the maximum it defines the random subset drawn on every visit; leaving both empty simply uses all of an image’s tags every time.\n\nA floor is worth setting when some images carry very few tags — a one-word prompt trains that word against the entire picture, background and all, which is a fast way to teach the model something you did not mean.",
  "tag-selection.max-tags-per-prompt":
    "The most tags a prompt may contain. This is the more useful of the two limits: showing the model a different handful each visit forces it to learn what each word contributes on its own, instead of memorising one long fixed list as a single unit.\n\nIt also keeps prompts within the model’s attention span — very long tag lists get progressively less attention toward the end, so 20 tags do not teach twice as much as 10. Something in the range of 8–20 is a common choice for heavily tagged libraries.",
  "tag-selection.pick-probability":
    "When a random subset of an image's tags goes into each prompt, uniform picking mirrors your library's imbalance: a tag on 400 images is learned 400× more often than one on 5, and the rare tag never really takes.\n\n'Balance rare tags' weights the draw by 1/frequency, so across the whole run every tag gets roughly comparable exposure. Use it when your dataset has a long tail you actually care about. It only changes WHICH tags are picked — see 'Weight loss by tag rarity' for the other lever, which changes how much each image counts.",
  "tag-selection.frequency-measured-in":
    "Rarity is relative to some population, and this picks which one.\n\n“Training data” counts only the images this job selected, so balancing works within the set you are actually training on — usually what you want. “Whole library” counts every item you own, which makes a tag that is common in your dataset but rare overall still count as rare. That is occasionally useful when the training set is a deliberate slice of a much larger, differently balanced collection.",
  "tag-selection.weight-loss-by-tag-rarity":
    "Pick probability changes which tags make it into a prompt. This changes how much a whole image counts once it is there: images whose tags are rare get a bigger say in each weight update, common ones a smaller one.\n\nThe multiplier is clamped between ×0.25 and ×4 so no single oddity can dominate a run. It is the right lever when the imbalance is in your images rather than in your tagging — five pictures of one character against four hundred of another. The two can be combined, but turn one on at a time so you can see what each did.",
  "tag-selection.skip-partially-matching-tags":
    "Booru-style tagging often carries a general tag alongside a specific one: “shirt” next to “white shirt”, “hair” next to “long hair”. In a prompt the pair is redundant, and worse, it teaches the model that the two words travel together — after which asking for “shirt” tends to give you a white one.\n\nWith this on, whenever a picked tag is a whole-word subset of another picked tag, the general one is dropped and a different tag is drawn in its place. The prompt keeps its length and gains a word that actually carries information.",
  "tag-selection.shuffle-tag-order":
    "Randomises the order of the tags in each prompt.\n\nPosition carries weight: words near the front get more attention than words near the end. With a fixed order, whatever your tagging tool happens to list first is systematically learned harder — and the model also picks up the order itself as a pattern, so prompts written differently at generation time work less well. Shuffling averages both effects out over the run. Leave it on unless you have a specific reason not to.",
  "tag-selection.caption-dropout":
    "Occasionally hands the model an image with NO prompt at all. That sounds pointless, but guidance (the CFG scale at generation time) works by comparing a prompted prediction against an unprompted one — so the unprompted path has to stay healthy.\n\nWithout any dropout, fine-tuning slowly degrades that path and generations get stiff and over-cooked at normal CFG values. 0.05–0.1 is the usual insurance; much higher just wastes steps.",
  "tag-selection.tag-separator":
    "The string put between tags when the prompt is assembled. Comma + space is what nearly every image model was trained on and what people type at generation time, so it is almost always the right answer.\n\nChange it only to match an unusual prompt convention — and if you do, remember that generation prompts should then use the same convention to get the same behavior.",
  "tag-selection.group-tags-by-tag-group":
    "A per-item tag group is usually about one thing in the picture — Alice's hair and dress, Bob's hat. Flattened into one comma list, the model is left to work out which adjective belongs to whom, and in a busy image it often gets it wrong.\n\nWith this on, the tags the random pick chose are laid out per group, in the order the pick produced, so shuffling still applies within a block. Tags in no group lead, because they describe the scene the groups sit inside. A tag that is in two groups is written under the first one — the same tag twice reads as emphasis and teaches nothing.",
  "tag-selection.label-each-block-with":
    "Puts something in front of each group's tags, so a block reads “Alice: blonde hair, dress” instead of “blonde hair, dress”.\n\nThe group's NAME is right when your groups are named for what they show. The SUBJECTS it is about are usually better: a group called “front figure” is bookkeeping, while the subject on it is “Alice” — the word you would actually type at generation time.\n\nA group with no subjects gets no label at all under that choice, rather than quietly falling back to its name.",
  "tag-selection.between-groups":
    "The string between one group's block and the next. A newline is the default because it is what makes the blocks read as separate statements rather than one longer list.\n\nIf your prompts are consumed somewhere that cannot carry line breaks, a distinctive string such as “ | ” works too — just use the same convention when you write generation prompts.",
  "tag-selection.write-tags-as-an-alias":
    "Your library's aliases are the other words for one thing — “cat”, “kitty”, “feline”. Assigning any of them stores the canonical name, so every prompt says the same word and the model learns to answer to that word alone; at generation time the others do less, or nothing.\n\nWith this above 0, each picked tag is sometimes written as one of its aliases instead. The roll happens per tag per visit, so one image seen twice reads differently and the whole vocabulary is spread across the run rather than one alias being chosen per tag and then repeated.\n\nOnly the PROMPT changes. Tag matching, the always/exclude lists, frequency balancing, the loss weight and the boxes a crop has to keep all keep using the canonical name — so this cannot skew any of them. A tag with no aliases is always written as itself, and 0 is exactly what every run did before this setting existed.",
  "tag-selection.write-tags-as":
    "A tag's comment is the one line beside its name in the Tags tab — “one girl in the picture” for `1girl`, “from below, looking up at the subject” for `from_below`. A booru vocabulary is compact for the people typing it and opaque to a text encoder; the comment is the same idea in words the encoder can read.\n\n“Their name” is what every run did: the tag as it is spelled. “Their comment” writes the comment in place of the name wherever a picked tag has one, and “Name and comment” writes the name with the comment in brackets after it, so the model learns both spellings of one thing. A tag with no comment is written as its name whatever this says.\n\nOnly the PROMPT changes. Matching, the always/exclude lists, frequency balancing, the loss weight and the boxes a crop has to keep all stay keyed on the tag's name, exactly as with aliases — and the comment is read from the library when the dataset is built, so editing a comment later changes the next run, not this one.",
  "tag-selection.underscores-to-spaces":
    "Tag vocabularies from booru sites write phrases with underscores — “looking_at_viewer”. The text encoder has no idea what that is; as plain words it does.\n\nWith this on, underscores become spaces in the training prompt, so the model learns ordinary English it can also understand when you type it later. Turn it off if you are deliberately training the underscore vocabulary itself, e.g. to match an existing anime model’s prompt style. Everything else — tag matching, always/exclude lists, frequency balancing — keeps using the raw tag names.",
  "test-samples.generate-test-samples":
    "Renders your test prompts with the model as it currently stands and files the results in the job’s timeline, so you can watch the concept appear — and notice it going wrong — while the run is still going.\n\nThis is what makes a long run recoverable: overfitting is obvious in the samples long before the loss curve says anything useful, and every sample sits next to the checkpoint from the same step, so a good-looking sample points directly at the file to keep.",
  "test-samples.cadence-measured-in":
    "A step is a fixed amount of work and an epoch is one pass over every training image, so the two cadences drift apart as a dataset grows — “every 250 steps” is most of a small run and a fraction of a big one, while “every epoch” means the same thing in both. It is the choice the checkpoint cadence and the run’s own length already offer, and setting all three the same way is what makes a sample, its checkpoint and a pass over your pictures line up in the timeline.\n\nHow many steps an epoch takes is worked out when the run starts, because only the built dataset knows how many entries it has — a film’s frames, a degraded copy and an item contributing one entry per caption all count.",
  "test-samples.generate-every":
    "Rendered after this many full passes over the dataset. The equivalent step count is printed in the job’s log when the run starts, so a glance there says what the cadence came out as for this particular dataset.\n\nSampling interrupts training while it renders, so on a large dataset one round per epoch may be further apart than you want and on a tiny one it may be a pause every few seconds — the log’s step figure is what tells you which.",
  "test-samples.generate-every-steps":
    "Rendered every this many steps, whatever the dataset is. 250–500 is a good rhythm: often enough to catch a concept going wrong, rare enough that the pauses do not dominate the run.",
  "test-samples.baseline-before-training":
    "Renders the same prompts once before training starts, using the untouched base model.\n\nWithout that reference it is genuinely hard to tell what your training did versus what the model could already do — especially for styles, where the base model often has an opinion of its own. It costs one sampling pass at the very beginning.",
  "test-samples.batch-size":
    "Sampling interrupts training to render your test prompts, so the time it takes is time not spent training. Rendering several at once amortises the fixed cost of a pipeline call, at the price of holding that many images in memory during a moment when the model, the optimizer state and the latents are already resident — which is exactly when memory is tightest. Raise it only if sampling is a noticeable pause and you have headroom.\n\nThe images are unaffected: each prompt keeps its own seed, so a batched sample is identical to an unbatched one.",
  "test-samples.sampler-steps":
    "Denoising steps used to render each test image (unrelated to training steps). 20–30 is plenty for a preview; more mostly costs time, and sampling pauses training while it runs.",
  "test-samples.cfg-scale":
    "How hard the sampler is pushed toward the prompt. Low values (2–4) drift free and look soft; high values (12+) follow the words rigidly and tend to over-saturate. 5–8 suits most models.\n\nFor test samples what matters is keeping it FIXED for the whole run — you are comparing steps against each other, so every other variable should stay put.",
  "test-samples.sample-seed":
    "The noise every test image starts from. Holding it fixed means two samples of the same prompt at different steps begin from exactly the same starting point, so any difference between them is training — not a different roll of the dice.\n\nThat is what makes the timeline readable as progress. Change it only if a particular seed happens to produce a misleading image for every step.",
  "transparency.use-alpha-as-a-loss-mask":
    "Only images that carry an alpha channel are affected, and only the LOSS is masked — weights are not spatial, so nothing here trains “part of” the model. What changes is how much each part of the picture is allowed to correct it: the visible subject counts fully, the transparent region counts for the background weight below.\n\nThe point is to stop the model learning the emptiness. Left unmasked, a cut-out’s background is just a large flat area the model dutifully learns to reproduce, and the subject ends up welded to it.\n\nTwo things worth knowing. The mask is applied in latent space, where one cell covers 8×8 pixels, so it goes soft at the edges and cannot isolate anything thinner than that — hair and whiskers are not maskable this way. And because the image encoder reaches across the alpha boundary, the transparent region is filled with a smooth extension of the subject’s edge colors before encoding, rather than left black; without that, the hard edge would be baked into the subject’s own latents where no mask can remove it.",
  "transparency.background-weight":
    "A hard 0 is tempting and usually too strong: the model then never sees a single example of what belongs around your subject, and generations put it in front of whatever the base model invents — often badly matched, because nothing ever taught it how the subject meets a background.\n\nA small weight keeps that signal without letting the empty area dominate the update. It also softens the latent-space edge problem: the fill is an approximation, and weighting it down rather than off means a slightly wrong fill costs you a little accuracy instead of nothing at all.",
  "validation.score-a-validation-loss":
    "The training loss cannot answer the question people ask of it. It is drawn from the pictures being trained on, at a different random noise level every step, so it is noisy by construction — and it keeps falling for as long as the model memorizes, which means it looks healthiest exactly when a run has gone on too long.\n\nThis scores two extra series that can answer it, both with the plain per-sample loss on a fixed seed, so every round asks the model exactly the same questions and the number moves only when the model does. The series appear as their own lines on the loss graph, and each round is a line in the job’s log.\n\nReading it: the validation loss falls while the model generalizes and flattens or turns when it starts memorizing — the turning point is roughly where to stop, and with step snapshots on, the checkpoint to pick. Expect it to sit above the training loss and to move in small amounts; what matters is the direction, not the level. It stays comparable across pauses, resumes and step extensions, because the scored images and the seed never change within a job.",
  "validation.validate-every":
    "How often a round runs, in steps. A round costs one forward pass per scored image — no gradients, no optimizer — so a 16-image set is a few seconds; matching the sample or checkpoint cadence keeps the graph, the images and the snapshots telling one story at the same steps.\n\nVery frequent rounds buy little: overfitting announces itself over hundreds of steps, not five.",
  "validation.held-out-images":
    "How many images are set aside for the validation loss. They are taken OUT of training entirely — never visited, in no pool, their captions never seen — because a loss over pictures the model is also memorizing measures nothing. The pick is random but fixed per job, whole images at a time (a picture cannot be half in training), regularization pools are not eligible, and it is capped at half the dataset so the setting can never eat the run it protects.\n\nMore images make a steadier line at a linearly higher cost per round. On a small dataset every held-out image is also a training image lost, which is the real price — 8–16 is usually enough to see the turn, and the job’s log says exactly how many were held out.",
  "validation.stable-loss-images":
    "A second series over ordinary TRAINING images: a fixed slice, re-scored with the same fixed seed each round. Nothing is held out — these stay in training — so it costs no data at all.\n\nWhat it shows is the training curve with the sampling noise removed. The per-step loss jumps around because every step draws different pictures at different noise levels; this line asks the same pictures at the same noise every time, so it is readable where the raw curve is a cloud. Compared against the held-out line it also localizes trouble: both falling is learning, stable falling while held-out rises is memorizing, and neither falling means the run is not learning at all.",
  "value-rules.value-rules":
    "Any tag shaped `<name>:<number><unit>` is a value tag — `people:3`, `height:172cm`, `height:1.72m`, or a ranking’s own `quality:7` — and a rule here turns a range of those numbers into words at prompt time: where `height` is greater than 190cm, write `tall`. A raw `height:172cm` token teaches a text encoder nothing it can read back at generation time; a word does.\n\nA matching tag is replaced by the rule’s text, and a per-rule toggle keeps the raw tag alongside for whoever wants both spellings in the prompt. The metric length and mass families convert, so one rule covers `172cm` and `1.72m` alike; an unknown unit compares only against the same unit, and a plain number only against plain numbers.\n\nRanges may overlap, and the first matching rule wins — the rows are dragged into order, and that order is part of the configuration. A value tag no rule matches passes through the prompt unchanged, so nothing is dropped silently. The rule’s phrase rides the ordinary random pick and dropout like the tag it replaced: prompts sometimes carry it and sometimes do not, which is exactly the variation score-tag conditioning wants.\n\nThe rules are resolved when the dataset is built — the job’s log says how many tags they matched — and a set of rules can be saved and loaded by name, so a house vocabulary is written once and reused across jobs. Loading a set adds its missing rules to the job rather than replacing the rows already there.",
  "videos.train-on-video-frames":
    "A video is not one picture, so it is normally left out of a dataset — which is why this is off by default.\n\nWith it on, every video the queries match is sampled at the interval below and each kept frame becomes an ordinary training image. A frame carries the video's untimed tags plus the timed ones whose range covers its moment, so a tag that only holds for one stretch of a film only teaches the frames from that stretch.\n\nThe frames live in the job's own folder and are thrown away when the run ends. They are re-extracted whenever the dataset is rebuilt, so a run that starts fresh always samples the video as it is now.",
  "videos.one-frame-every":
    "A film is tens of thousands of near-identical pictures, and training on all of them would teach the model one scene very thoroughly and everything else not at all.\n\nSeconds is the natural unit: time ranges on tags are in seconds, and frame rates differ between files. Counting in frames is there for short clips where you know the rate and want a fixed stride.",
  "videos.drop-repeated-frames":
    "Sampling at a fixed interval treats a still title card and a fast action scene alike, and a held shot then arrives in the dataset once per interval it lasts — outweighing everything the film actually shows.\n\nWith this on, a frame that looks like one already kept from the same video is dropped. The comparison is the same perceptual hash the importer uses to spot duplicate images, so “the same picture” means here what it means everywhere else in the library.",
  "videos.the-films-captions":
    "A caption sits on the video, so a frame can only take all of them or none — a tag has time ranges to say when it holds, and a caption has not.\n\nThat matters because plenty of captions describe the film rather than any one moment of it: “a fight scene set to music”, “episode three, the beach”. Training a still against one of those teaches the model to draw what a sentence says happens over minutes.\n\nWith inheriting off, frames carry no caption text. On a tags run that costs nothing; on a captions run it means the film contributes no frames at all, because a frame with nothing to build a prompt from is left out rather than trained against an empty one.",
  "videos.frames-only-inherit-captions-tagged":
    "The finer answer to the same question: rather than take all of a film's captions or none, label the ones that describe a moment and name that label here.\n\nThese lists narrow what the run's own caption selection already allows — they never widen it, so a caption the run excludes cannot come back through a film.",
  "videos.frames-never-inherit-captions-tagged":
    "Usually the easier half to maintain: name the few kinds of caption that are about the film — a plot summary, an episode note, a line about the soundtrack — and leave everything else to reach the frames.\n\nExcluding wins over including, so a caption carrying both an included and an excluded tag is not inherited.",
  "weight-averaging.average-the-weights":
    "Every training step moves the weights a little, and each of those moves is noisy — it is worked out from a handful of images, and a different handful would have pulled somewhere slightly different. So the weights at step 1400 are not reliably better than the weights at step 1200; part of the difference is just which pictures came up.\n\nWith this on, the run keeps a second, smoothed copy of the weights alongside the real ones and nudges it a little way towards the current weights after every step. That smoothed copy is what gets saved — as the checkpoints, as the final result, and as what the test samples are rendered from. Training itself is completely unaffected.\n\nWhat you get is a result that depends less on exactly where the run stopped: the quality difference between neighbouring checkpoints shrinks, and a run that goes on too long degrades more gradually, because an average lags behind. What it costs is one extra copy of whatever is being trained — nothing worth thinking about for a LoRA, a second whole model for a full finetune, which the memory estimate below accounts for.\n\nThe early part of a run is handled for you: a fresh average starts out equal to the untrained weights, so the run keeps it short at first and lengthens it as training goes on. Without that, a short run would save an average still holding its own random starting point.",
  "weight-averaging.averaging-window":
    "The fraction of the existing average kept at each step, with the rest taken from the current weights. It decides how long a stretch of training the saved result reflects — roughly 1 ÷ (1 − this value) steps.\n\n0.999 is about the last 1000 steps and is a sensible default for runs of a few thousand. On a short run (say 800 steps) that window is longer than the run itself, so the average never quite catches up — drop to 0.99 (about 100 steps) there. On a very long run you can go higher for a steadier result.\n\nAs a rule of thumb, keep the window well under the total number of steps.",
};
